services:
  backend:
    build:
      context: ./backend
      dockerfile: fastAPI/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/raw:/app/raw
      - ./backend/data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload